github:
  description: "Apache Fineract"
  homepage: https://fineract.apache.org
  labels:
    - apache
    - banking
    - finance
    - fintech
    - group-lending
    - group-savings
    - java
    - lending
    - loans
    - microfinance
    - savings
    - social-impact
    - tech4good
